name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Install and cache dependencies
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build Remix App
        run: |
          npm ci
          npm run build
        env:
          REMIX_REGISTRY_TOKEN: ${{ secrets.REMIX_REGISTRY_TOKEN }}
      - uses: actions/checkout@v2
      - run: "sed -i 's/${REMIX_REGISTRY_TOKEN}/${REGISTRY_TOKEN}/' .npmrc"
        shell: bash
        env:
          REGISTRY_TOKEN: ${{secrets.REMIX_REGISTRY_TOKEN}}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPODCAST_CD96F }}'
          channelId: live
          projectId: spodcast-cd96f
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
